name: Build and Deploy Miketur

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixa o código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instala dependências
      - name: Install dependencies
        run: npm install

      # Gera o build final
      - name: Build project
        run: npm run build

      # Publica no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
